name: Deploy to VPS

on:
  workflow_run:
    workflows:
      - Build and Push
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.DO_HOST }}
          username: ${{ vars.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull imhasib/sirr-web-admin:latest
            docker compose -f /root/speaking-club-deployment/docker-compose.yml up -d --no-build
